### ISSUE TITLE
Inject into executable path option

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule-rw#1]
Hey, I know this is still pretty new but I was wondering if the -p option is going to be added to cyan too. Thanks!

**Comment by k3v1nwrld** [comment]
> nope, it's useless, and cyan aims to remove some of the garbage from pyzule

What about tweaks like Watusi/Regram that crash if not injected to the executable path?? I'm guessing that's gonna be a problem since you use them too no?

**Comment by asdfzxcvbn** [comment]
> > nope, it's useless, and cyan aims to remove some of the garbage from pyzule
> 
> 
> 
> What about tweaks like Watusi/Regram that crash if not injected to the executable path?? I'm guessing that's gonna be a problem since you use them too no?

huh? no they dont, are you using the debs for those tweaks? they arent meant to be injected into ipas

extract the tweaks from an existing ipa meant for sideloading and inject those, it'll work

**Comment by asdfzxcvbn** [comment]
> > > > nope, it's useless, and cyan aims to remove some of the garbage from pyzule
> > > 
> > > 
> > > What about tweaks like Watusi/Regram that crash if not injected to the executable path?? I'm guessing that's gonna be a problem since you use them too no?
> > 
> > 
> > huh? no they dont, are you using the debs for those tweaks? they arent meant to be injected into ipas
> > extract the tweaks from an existing ipa meant for sideloading and inject those, it'll work
> 
> Actually no, Fouad the developer of Regram always advice ppl to copy files & inject Regram.dylib into executable path ( for those with IPAs & sideloading). I used pyzule alot, and always used -p option with it, I hope to see it in Cuan.
> 
> You can add it, if its needed, user just can pass it in command.
> 
> Much appreciated.

oh yeah, i remember this, it actually works completely fine without it in @executable_path ,, he just hardcoded a check to make sure it's there. kinda nonsensical.. i can send you a patched dylib if you message me on telegram however, this feature wont be added to cyan

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn Yes, same files and same flags...
> 
> `pyzule -i IG356.ipa -o IG356_Tweaked.ipa -f Regram.dylib Regram.Bundle/ libWatusiToolsSL.dylib WatusiTools.bundle/ -p`
> 
> and Cyan:
> 
> `cyan -i IG356.ipa -o IG356_Tweaked.ipa -f Regram.dylib Regram.Bundle/ libWatusiToolsSL.dylib WatusiTools.bundle/ `
> 
> 
> 
> both worked, BUT with Cyan I need to go and refresh my license (already logged in) in order to use features & IT HAPPENS EVERYTIME I close app and re-open it...
> 
> 
> 
> I tried with Sideloadly too (Just exporting ipa), same thing...
> 
> 
> 
> Worked without any issues with pyzule, u can try it ur self.

this is literally what i just told you lol

> it actually works completely fine without it in @executable_path ,, he** just hardcoded a check to make sure it's there**. kinda nonsensical.. i can send you a patched dylib if you message me on telegram

fouad makes this an issue on purpose for no real reason. also you didnt use the same flags, cyan doesnt even have -p ... also why is your ".bundle" capatalized?
