### ISSUE TITLE
[bug] Sideloadly can't install apps sideloaded with cyan/pyzule

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule-rw#4]
### have you searched the existing issues?

- [X] this is a unique issue. i agree that if this isn't a unique issue, i'll be BLOCKED from the cyan repo

### describe the bug.

![Screenshot_1](https://github.com/user-attachments/assets/66aea30e-3db8-434e-af42-eb6ffc09081f)
Here's the screenshot of the error I get when trying to install apps with Sideloadly. This error has popped up recently, cuz last week I was able to install apps normally. Thanks

Edit: Btw I injected a couple of tweaks into the app and used these flags -uwg

**Comment by asdfzxcvbn** [comment]
and it works with the raw decrypted ipa?
