### ISSUE TITLE
[feature request] Extract debs/dylibs

### ISSUE THREAD

**Issue by TestAccountFooBar** [asdfzxcvbn/pyzule-rw#5]
### have you searched the existing issues?

- [X] this is a unique feature request. i agree that if this isn't a unique request, i'll be BLOCKED from the cyan repo

### describe the feature request.

This essentially means injecting a tweak in reverse, i.e. taking the modified ipa and obtaining the untouched ipa and the tweaks that have been injected into it. Afaik the only tool for extracting tweaks from a modified ipa is the closed-source app esign.

**Comment by asdfzxcvbn** [comment]
you said it yourself, it's pretty much the opposite of cyan's goal

i admit this is a pretty nice thing to be able to do, however it's out of scope for this project

p.s. it definitely is possible and i've already done it before, and a seperate tool could be made exclusively for doing this, but i have no problem using esign for this (well, ESignNoLogs)

**Comment by asdfzxcvbn** [comment]
> That's reasonable.
> 
> > p.s. it definitely is possible and i've already done it before, and a seperate tool could be made exclusively for doing this, but i have no problem using esign for this (well, ESignNoLogs)
> 
> 
> 
> Do you know of any ways other than esign, such a command line tools or ones that work on desktop platforms? Esign's a bit trickier to deal with for my purposes.
> 
> 

theres no cli tool for it really, but it's possible with lief (the library used for injection in pyzule and linux arm64 injection in cyan)
