### ISSUE TITLE
Cyan can't be reached via shortcut ssh

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule-rw#9]
So long story short, I use a telegram bot to decrypt ipas and send them over via a shortcut to my raspberry pi, which has a bash script that injects debs with cyan whenever certain file names are found (ex: Instagram.ipa). This used to work fine for me with pyzule, but when cyan came out, it broke. I think part of the reason is because it can't find cyan's path (I've tried making a variable that points to $(which cyan) but that doesnt work too). Do you have any idea how I could try to fix this?? Im completely lost. Thanks!

**Comment by asdfzxcvbn** [comment]
> So long story short, I use a telegram bot to decrypt ipas and send them over via a shortcut to my raspberry pi, which has a bash script that injects debs with cyan whenever certain file names are found (ex: Instagram.ipa). This used to work fine for me with pyzule, but when cyan came out, it broke. I think part of the reason is because it can't find cyan's path (I've tried making a variable that points to $(which cyan) but that doesnt work too). Do you have any idea how I could try to fix this?? Im completely lost. Thanks!

you know me on tele right? it'd be easier to help there than through gh issues

**Comment by asdfzxcvbn** [comment]
author installed cyan through pipx

fixed by adding `export PATH=$HOME/.local/bin:$PATH` as the first line in their script, it works i guess
